version: '3.3'

services:

  back:
  
      build: back/

      container_name: back
      
      volumes:
         - ./back:/home/dev/
           
      command: bash -c "npm install && npm run start:dev"
        
      ports:
         - 3000:3000
      
      env_file:
         - env.envar

      depends_on:
         - mongo

  mongo:
   
      image: mongo:4.4.6
      
      container_name: mongo
         
      env_file:
         - env.envar
      
      expose:
         - "27017/tcp"

#   mongo-express:
#       image: mongo-express
#       restart: unless-stopped
#       ports:
#          - 8081:8081
#       environment:
#          ME_CONFIG_MONGODB_ADMINUSERNAME: test
#          ME_CONFIG_MONGODB_ADMINPASSWORD: test
#          ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/
   
#       depends_on:
#          - mongo

  front:

      build: front/

      container_name: front
      
      volumes:
         - ./front:/home/app/angular
            
      # command: bash -c "npm install && ng serve --host=front"
      command: bash -c "ng serve --host=front"
      # command: /bin/bash
        
      ports:
         - 4200:4200
    